name: Build and Release AppBlocker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile app_blocker/main.py --name AppBlocker

      - name: Get current date
        id: date
        shell: bash
        run: echo "release_date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Generate changelog from last tag or commit
        id: changelog
        shell: bash
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            CHANGELOG=$(git log "$LAST_TAG"..HEAD --pretty=format:"- %s")
          else
            CHANGELOG=$(git log -n 10 --pretty=format:"- %s")
          fi

          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.release_date }}
          tag_name: release-${{ steps.date.outputs.release_date }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: dist/AppBlocker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
