name: Build and Release AppBlocker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:  # Manual trigger support

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile app_blocker/main.py --name AppBlocker

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: AppBlocker
          path: dist/AppBlocker.exe
