name: Build and Release AppBlocker

on:
  push:
    branches:
      - main # Triggers on pushes to the main branch
    tags:
      - 'v*' # Also triggers on version tags like v1.0, v0.2.1
  workflow_dispatch: # Allows manual triggering via GitHub UI

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    permissions: # Required for softprops/action-gh-release
      contents: write # To create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assumes requirements.txt will be created
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller AppBlocke
