name: Build and Release AppBlocker

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for getting full history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile app_blocker/main.py --name AppBlocker

      - name: Get current date
        id: date
        shell: bash
        run: echo "release_date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Generate full changelog and contributors
        id: changelog
        shell: bash
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            RANGE="$LAST_TAG..HEAD"
            TAG_TITLE="Commits since \`$LAST_TAG\`"
          else
            RANGE="HEAD"
            TAG_TITLE="Recent Commits"
          fi

          echo "### 📦 Auto-generated Changelog" > changelog.md
          echo "These changes were automatically generated based on commits." >> changelog.md
          echo "" >> changelog.md
          echo "#### 🔨 $TAG_TITLE" >> changelog.md
          git log $RANGE --pretty=format:"- %h - %s (by %an)" >> changelog.md
          echo "" >> changelog.md
          echo "#### 👥 Thanks to Contributors" >> changelog.md
          git log $RANGE --format='%an' | sort -u | sed 's/^/- /' >> changelog.md

          {
            echo "changelog<<EOF"
            cat changelog.md
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.release_date }}
          tag_name: release-${{ steps.date.outputs.release_date }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: dist/AppBlocker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
